# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0002_auto_20161023_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='empname',
            new_name='employeeinfo',
        ),
    ]
