# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0004_auto_20161023_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegator', models.CharField(max_length=50)),
                ('delegated', models.CharField(max_length=50)),
                ('dbuilding', models.CharField(default='all', max_length=10)),
                ('dfloor', models.CharField(default='all', max_length=10)),
                ('dwing', models.CharField(default='all', max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='empname',
            new_name='assignee',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='building',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='room',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='photo',
        ),
        migrations.AddField(
            model_name='assignment',
            name='abuilding',
            field=models.CharField(default='temp', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='afloor',
            field=models.CharField(default='temp', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='aroom',
            field=models.CharField(default='temp', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignor',
            field=models.CharField(default='temp', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
