# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0005_auto_20161130_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='abuilding',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='afloor',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='aroom',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignor',
            field=models.CharField(max_length=50),
        ),
    ]
