# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0006_auto_20161130_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='delegated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.EmployeeInfo'),
        ),
    ]
